### PR TITLE
Fixed a compilation error in Repeat pattern.

### PR DESCRIPTION
**Pull request by itozyun**
~~~js
RegExp('(E{0,2})').exec('EE')
[ "EE", "EE" ]

RegExpCompat('(E{0,2})').exec('EE')
null
~~~

repeat

### CODE REVIEW

**Comment by MakeNowJust** [comment]
@itozyun Thank you!

A test case for this fix lacks. Could you add such a test case?

**Comment by itozyun** [comment]
@MakeNowJust I wrote it, now just!

**Review by MakeNowJust — APPROVED** [review]
LGTM 👍

**Comment by itozyun** [comment]
(*^-^*)

**Pull request merged**
